CREATE TABLE IF NOT EXISTS groups (
    uuid UUID PRIMARY KEY,
    group_id BIGINT NOT NULL UNIQUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
